baseURL = 'https://blog.hyunsang.dev/'
languageCode = 'ko-kr'
title = 'HyunSang Park'

# RSS 설정
enableRobotsTXT = true
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[build]
  writeStats = true
  # 빌드 성능 최적화
  useResourceCacheWhen = "always"

  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx|css)"
    target = "(css|js)"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

# 캐시 설정
[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "8760h"  # 1년
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "8760h"
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "8760h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "8760h"
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "8760h"

[params]
  description = "HyunSang's Software Engineering Blog"
  author = 'Hyunsang Park'
  profileImage = 'images/profile.jpeg'
  bio = '사이버 보안을 전공하고 있습니다. 문학과 철학을 애증합니다.'

  [[params.social]] 
    name = 'Website'
    url = 'https://hyunsang.dev'
  [[params.social]]
    name = 'GitHub'
    url = 'https://github.com/dev-hyunsang'

  [[params.social]]
    name = 'LinkedIn'
    url = 'https://linkedin.com/in/parkhyunsang'

  [[params.social]]
    name = 'Email'
    url = 'mailto:me@hyunsang.dev'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[taxonomies]
  category = 'categories'
  tag = 'tags'


[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 1

  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 2

  [[menu.main]]
    name = 'Categories'
    url = '/categories/'
    weight = 3

  [[menu.main]]
    name = '밑줄 친 문장들'
    url = '/highlights/'
    weight = 4
